name: Build & Sync Packages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  detect:
    name: Detect Changed Packages
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Install git
        run: pacman -Sy --noconfirm git

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Find updated or changed packages
        id: set-matrix
        run: |
          cd main

          changed=()
          for pkg in */PKGBUILD; do
