name: Build & Sync Packages

on:
  push:
    branches:
      - main
      - test

  workflow_dispatch:

jobs:
  detect:
    name: Detect Changed Packages
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Prepare build system
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm git jq

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main

      - name: Get previous hashes
        id: prev-hashes
        run: |
          if [ -f "main/package_hashes.txt" ]; then
            echo "hashes=$(cat main/package_hashes.txt | jq -sR .)" >> $GITHUB_OUTPUT
          else
            echo "No existing hashes file found"
            echo "hashes=" >> $GITHUB_OUTPUT
          fi

      - name: Find changed packages using hashes
        id: set-matrix
        run: |
          cd main

          # Create array of changed packages
          changed=()
          declare -A prev_hashes
          
          # Load previous hashes if they exist
          if [ -n '${{ steps.prev-hashes.outputs.hashes }}' ]; then
            while IFS=: read -r path hash; do
              prev_hashes["$path"]=$hash
            done <<< $(echo '${{ steps.prev-hashes.outputs.hashes }}' | jq -r . | grep .)
          fi

          # Generate current hashes and compare
          current_hashes=()
          for pkg in packages/*/PKGBUILD; do
            dir=$(dirname "$pkg")
            echo "Checking $dir"
            
            # Generate current .SRCINFO
            (cd "$dir" && makepkg --printsrcinfo > .SRCINFO.current)
            
            # Calculate current hash
            current_hash=$(sha256sum "$dir/.SRCINFO.current" | awk '{print $1}')
            current_hashes+=("$dir:$current_hash")
            
            # Compare with previous hash if it exists
            if [[ -v prev_hashes["$dir"] ]]; then
              if [[ "${prev_hashes["$dir"]}" != "$current_hash" ]]; then
                echo "$dir hash changed (was ${prev_hashes["$dir"]}, now $current_hash)"
                changed+=("$dir")
              fi
            else
              echo "$dir has no previous hash, will build"
              changed+=("$dir")
            fi
          done

          # Output new hashes for next run
          printf "%s\n" "${current_hashes[@]}" > package_hashes.txt
          
          # Create build matrix
          if [ ${#changed[@]} -eq 0 ]; then
            echo "No packages changed"
            echo 'matrix={"include":[]}' >> $GITHUB_OUTPUT
          else
            matrix=$(jq -nc '$ARGS.positional' --args -- "${changed[@]}")
            matrix="{\"include\":$(echo "$matrix" | jq -c 'map({pkg: .})')}"
            echo "matrix=$matrix" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated hashes
        if: always()
        run: |
          cd main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package_hashes.txt
          git commit -m "Update package hashes [CI]" || echo "No changes to commit"
          git push

  build:
    name: Build ${{ matrix.pkg }}
    needs: detect
    if: needs.detect.outputs.matrix != '{"include":[]}'
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

    steps:
      - name: Configure pacman mirrorlist
        run: |
          sudo sed -i 's|Server = http://mirror.archlinuxarm.org/$arch/$repo|# Server = http://mirror.archlinuxarm.org/$arch/$repo|g' /etc/pacman.d/mirrorlist
          sudo sed -i 's|# Server = http://eu.mirror.archlinuxarm.org/$arch/$repo|Server = http://eu.mirror.archlinuxarm.org/$arch/$repo|g' /etc/pacman.d/mirrorlist

      - name: Update system
        run: sudo pacman -Syu --noconfirm

      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install tools
        run: sudo pacman -S --noconfirm base-devel git jq gnupg

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo RELOADAGENT | gpg-connect-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure makepkg
        run: |
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          echo "GPGKEY=$KEYID" >> ~/.makepkg.conf
          echo "PACKAGER='Arch Package Builder <build@tx0.su>'" >> ~/.makepkg.conf
          echo "MAKEFLAGS='-j$(nproc)'" >> ~/.makepkg.conf
          echo "PKGEXT='.pkg.tar.xz'" >> ~/.makepkg.conf
          echo "SRCEXT='.src.tar.gz'" >> ~/.makepkg.conf

      - name: Build package ${{ matrix.pkg }}
        run: |
          cd main/${{ matrix.pkg }}
          makepkg --noconfirm -s --sign
          mkdir -p ../../../artifacts/${{ matrix.pkg }}/
          cp *.pkg.tar.* ../../../artifacts/${{ matrix.pkg }}/

      - name: Set artifact name
        run: |
          SAFE_NAME="${{ matrix.pkg }}"
          SAFE_NAME="${SAFE_NAME//\//-}"
          echo "ARTIFACT_NAME=$SAFE_NAME" >> $GITHUB_ENV
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ env.ARTIFACT_NAME }}
          path: artifacts/${{ matrix.pkg }}/*.pkg.tar.*
          retention-days: 1

  update-repo:
    name: Update Repository
    needs: build
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    steps:
      - name: Install pacman and tools
        run: sudo pacman -Sy --noconfirm pacman gnupg

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: repo

      - name: Download all package artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy packages to repository
        run: |
          find artifacts -name "*.pkg.tar.*" -exec cp {} repo/ \;
          rm -rf artifacts

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo RELOADAGENT | gpg-connect-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure GPG for repo-add
        run: |
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          echo "GPGKEY=$KEYID" >> ~/.makepkg.conf
          echo "PACKAGER='Arch Repo Builder <repo@tx0.su>'" >> ~/.makepkg.conf

      - name: Update repository database
        run: |
          cd repo
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          repo-add -n -k $KEYID -R pipa-alarm.db.tar.gz *.pkg.tar.xz

      - name: Commit and push changes
        run: |
          cd repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update repository with new packages [CI]" || echo "No changes to commit"
          git push
