name: Build & Sync Packages

on:
  push:
    branches:
      - main
      - test

  workflow_dispatch:

jobs:
  detect:
    name: Detect Changed Packages
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Prepare build system
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm git jq

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Find updated or changed packages
        id: set-matrix
        run: |
          cd main

          changed=()
          for pkg in packages/*/PKGBUILD; do
            dir=$(dirname "$pkg")
            echo "Checking $dir"
          
            (cd "$dir" && makepkg --printsrcinfo > .SRCINFO.generated)
          
            if [ ! -f "$dir/.SRCINFO" ]; then
              echo "$dir has no .SRCINFO, will build"
              changed+=("$dir")
              continue
            fi
          
            if ! diff -q "$dir/.SRCINFO" "$dir/.SRCINFO.generated" >/dev/null; then
              echo "$dir .SRCINFO differs, will build"
              changed+=("$dir")
            fi
          done
          
          if [ ${#changed[@]} -eq 0 ]; then
            echo "No packages changed"
            echo 'matrix={"include":[]}' >> $GITHUB_OUTPUT
          else
            matrix=$(jq -nc '$ARGS.positional' --args -- "${changed[@]}")
            matrix="{\"include\":$(echo "$matrix" | jq -c 'map({pkg: .})')}"
            echo "matrix=$matrix" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build ${{ matrix.pkg }}
    needs: detect
    if: needs.detect.outputs.matrix != '{"include":[]}'
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

    steps:
      - name: Configure pacman mirrorlist
        run: |
          sudo sed -i 's|Server = http://mirror.archlinuxarm.org/$arch/$repo|# Server = http://mirror.archlinuxarm.org/$arch/$repo|g' /etc/pacman.d/mirrorlist
          sudo sed -i 's|# Server = http://eu.mirror.archlinuxarm.org/$arch/$repo|Server = http://eu.mirror.archlinuxarm.org/$arch/$repo|g' /etc/pacman.d/mirrorlist

      - name: Update system
        run: sudo pacman -Syu --noconfirm

      - name: Setup git
        run: |
          git config --global user.name Builder
          git config --global user.email builder@tx0.su

      - name: Install tools
        run: sudo pacman -S --noconfirm base-devel git jq gnupg

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo RELOADAGENT | gpg-connect-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure makepkg
        run: |
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          echo "GPGKEY=$KEYID" >> ~/.makepkg.conf
          echo "PACKAGER='Arch Package Builder <build@tx0.su>'" >> ~/.makepkg.conf
          echo "MAKEFLAGS='-j$(nproc)'" >> ~/.makepkg.conf
          echo "PKGEXT='.pkg.tar.xz'" >> ~/.makepkg.conf
          echo "SRCEXT='.src.tar.gz'" >> ~/.makepkg.conf

      - name: Build package ${{ matrix.pkg }}
        run: |
          cd main/${{ matrix.pkg }}
          makepkg --noconfirm -s
          mkdir -p ../../../artifacts/${{ matrix.pkg }}/
          cp *.pkg.tar.* ../../../artifacts/${{ matrix.pkg }}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ format('{0}', matrix.pkg).replace('/', '-') }}
          path: artifacts/${{ matrix.pkg }}/*.pkg.tar.*
          retention-days: 1

  update-repo:
    name: Update Repository
    needs: build
    runs-on: ubuntu-24.04-arm

    container:
      image: ghcr.io/nabu-alarm/archlinux-builder:latest

    steps:
      - name: Install pacman and tools
        run: sudo pacman -Sy --noconfirm pacman gnupg

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: repo

      - name: Download all package artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy packages to repository
        run: |
          find artifacts -name "*.pkg.tar.*" -exec cp {} repo/ \;
          rm -rf artifacts

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo RELOADAGENT | gpg-connect-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure GPG for repo-add
        run: |
          KEYID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ { print $5; exit }')
          echo "GPGKEY=$KEYID" >> ~/.makepkg.conf
          echo "PACKAGER='Arch Repo Builder <repo@tx0.su>'" >> ~/.makepkg.conf

      - name: Update repository database
        run: |
          cd repo
          repo-add -n -R pipa-alarm.db.tar.gz *.pkg.tar.*

      - name: Commit and push changes
        run: |
          cd repo
          git config user.name "Builder"
          git config user.email "builder@tx0.su"
          git add .
          git commit -m "Update repository with new packages [CI]" || echo "No changes to commit"
          git push
